// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1wR5x4OdO8_R6E-Dau-5p8ZiVoj98S5I',
    appId: '1:205058012615:web:9c05e617c3f003548e15e2',
    messagingSenderId: '205058012615',
    projectId: 'kotobanotis',
    authDomain: 'kotobanotis.firebaseapp.com',
    storageBucket: 'kotobanotis.firebasestorage.app',
    measurementId: 'G-YLLJP0339S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMYU1AL8ZyZzjgdatN8B9PHBbx8dKT5Tc',
    appId: '1:205058012615:android:1ccb615e15a6a3fd8e15e2',
    messagingSenderId: '205058012615',
    projectId: 'kotobanotis',
    storageBucket: 'kotobanotis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbT6bDEGUiMrgDj5WI7a6CkDVmpzgbeHY',
    appId: '1:205058012615:ios:ebd86b81e7c5955f8e15e2',
    messagingSenderId: '205058012615',
    projectId: 'kotobanotis',
    storageBucket: 'kotobanotis.firebasestorage.app',
    iosBundleId: 'com.example.kotobaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbT6bDEGUiMrgDj5WI7a6CkDVmpzgbeHY',
    appId: '1:205058012615:ios:ebd86b81e7c5955f8e15e2',
    messagingSenderId: '205058012615',
    projectId: 'kotobanotis',
    storageBucket: 'kotobanotis.firebasestorage.app',
    iosBundleId: 'com.example.kotobaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1wR5x4OdO8_R6E-Dau-5p8ZiVoj98S5I',
    appId: '1:205058012615:web:ffb98e6bf2be96328e15e2',
    messagingSenderId: '205058012615',
    projectId: 'kotobanotis',
    authDomain: 'kotobanotis.firebaseapp.com',
    storageBucket: 'kotobanotis.firebasestorage.app',
    measurementId: 'G-TZD4Y2C93X',
  );
}
